### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bugadani**
Hi! Nice crate, thanks :) This PR updates some of the dependencies so that my application can have fewer duplicated ones. Hope you don't mind :)

### CODE REVIEW

**Comment by rib** [comment]
Thanks for the PR @bugadani, these dep tweaks look fine to me. I wonder if I should also bump to a 1.0 release, considering I haven't really found I've needed to make changes to the api for some time.

**Comment by bugadani** [comment]
@rib as you wish :) I'd think a stable release would do some good in terms of adoption: 13 alphas, the last of which was released 9 months ago may suggest to potential users that the crate isn't developed any more. Even though the reality isn't that the crate is abandoned, but that it's considered good enough.

To be honest, for my use case, the crate isn't exactly convenient, but I might be misusing JWTs a bit and this PR isn't the place for my complaints I think.

**Comment by rib** [comment]
I'm all ears if you're finding it's actually not as convenient to use as you would have hoped. I might not have lots of time to fix it right now, but generally the only reason I haven't updated it recently is just that it was serving my needs well and I never circled back to make a 1.0 release after giving the alpha time to settle.

Discussion here is probably fine if convenient, but just switched on the new discussions feature too in case that works for describing any mild complaints/api thorns.

**Comment by bugadani** [comment]
In the end, what's currently implemented works well enough for me as well. But I'll try to organize my thoughts sometime and start a discussion about them. No promises though :)

**Comment by rib** [comment]
Cool thanks, no worries, and understand if you don't end up getting the chance to follow up, but would also be interested to hear more about your use case out of curiosity.

**Pull request merged**
