### PR TITLE
feat(threading): add markers for sharing VerififerClosure across threads

### PR DESCRIPTION
**Pull request by robertohuertasm**
Hi, I'm using this crate along with `jsonwebtokens-cognito` while building a gRPC server with `Tonic`. As there we need to use `async traits` which expand to `Sync + Send` functions I got some errors while using your crate. 

Ultimately, I needed the `VerifierClosure` function to be `Send + Sync`. Just by adding the markers it worked. I'm not sure if this was something you explicitly opted out. I'm happy to discuss it in order to find a solution that works for everyone.

Thanks for these crates!!

### CODE REVIEW

**Comment by robertohuertasm** [comment]
By the way, I separated the changes in two different commits. I noticed you didn't use cargo-fmt. My editor formats the code by default, so the first commit is just for formatting purposes and the second one has the real changes.

**Comment by robertohuertasm** [comment]
The beta pipeline failed because a network error.

**Comment by rib** [comment]
Thanks for separating the formatting change (I should probably figure out using cargo-fmt too at some point).

I'm also using these with a Tonic gRPC service (though maybe didn't update that since I added the closure-based claims verifier) so I guess I would have hit the same issue eventually too, so thanks for the fix!

**Comment by rib** [comment]
Just to mention that I've also just published an -alpha.13 point release including this change - thanks

**Comment by robertohuertasm** [comment]
Thanks for merging this! 

I was thinking that maybe it would make sense to move the `jsonwebtokens-cognito` here and use a `workspace` here with all the related crates. By doing this it may be easier to make modifications or fixes when both crates need to change. I could do a PR with `github actions` support both for building and publishing to crates.io.

**Comment by robertohuertasm** [comment]
> Just to mention that I've also just published an -alpha.13 point release including this change - thanks

Thanks a lot!

Unfortunately, I also need the version to be updated in `jsonwebtokens-cognito`, but maybe you're already on it 😜

**Comment by robertohuertasm** [comment]
I have some ideas to implement some procedural macros to help with tonic services authentication that could benefit from a `worspaced` project 😉.

**Comment by rib** [comment]
> Unfortunately, I also need the version to be updated in jsonwebtokens-cognito, but maybe you're already on it 😜

In jsonwebtokens-cognito the jsonwebtokens dependency version is specified as `1.0.0-alpha` (without the .13) so doesn't it just Just Work™ for you? I just ran `cargo update` and that pulled in in the .13 release for me.

**Comment by rib** [comment]
> I have some ideas to implement some procedural macros to help with tonic services authentication that could benefit from a worspaced project 😉.

Okey - I haven't played with procedural macros yet, but yeah it sounds like they have to be in a separate crate so I guess it's convenient from the pov of experimenting with a branch is what you're thinking? You're thinking of some kind of jsonwebtokens-tokio-macros crate with some helpers?

Moving jsonwebtokens-cognito into a common repo could be reasonable and having github actions support sounds good to me, if you did want to take a poke at that. Would ideally be good if jsonwebtoken-cognito history wasn't lost if we did that by e.g. using `git filter-tree` to combine.

**Comment by robertohuertasm** [comment]
> In jsonwebtokens-cognito the jsonwebtokens dependency version is specified as 1.0.0-alpha (without the .13) so doesn't it just Just Work™ for you? I just ran cargo update and that pulled in in the .13 release for me.

You're absolutely right! I had the `.13` in the dependency and haven't thought about removing it 🤦

**Comment by robertohuertasm** [comment]
> Okey - I haven't played with procedural macros yet, but yeah it sounds like they have to be in a separate crate so I guess it's convenient from the pov of experimenting with a branch is what you're thinking? You're thinking of some kind of jsonwebtokens-tokio-macros crate with some helpers?

Yes, I guess most of the people will want to customize which methods of the service require authorization so I was thinking that something like an attribute macro indicating which function requires authorization that could provide automatic extraction of the token from the Tonic request and validate it against Cognito would be nice.

I'm not sure how you're handling that in your gRPC project, but I found that interceptors in Tonic don't allow async methods. I guess I could use `try_verify` and `prefetch_jwks` before, though, but I prefer to be granular regarding authorization and specify which endpoints need it.

>Moving jsonwebtokens-cognito into a common repo could be reasonable and having github actions support sounds good to me, if you did want to take a poke at that. Would ideally be good if jsonwebtoken-cognito history wasn't lost if we did that by e.g. using git filter-tree to combine.

Sounds good to me 👍 

Thanks again for your support!

**Comment by rib** [comment]
Right, I'm currently using an interceptor and prefetch the jwks upfront due to not having an async context at that point. In my case I only have one authentication model to worry about for all requests and it's convenient to handle that in one place and not worry about making a mistake authenticating each request separately. The synchronous interceptors in Tonic is essentially what made me add the `prefetch_jwks` and `try_verify` APIs.

I think I found that Amazon were documenting somewhere that they don't do any kind of key rotation and so I think you can generally assume that once you've fetched the jwks key set that shouldn't get out-of-date.

I can see that it could also be reasonable to defer the authentication until you are async and also be more fine grained with perhaps having some requests not be authenticated.

You do have access to the request within the interceptor so you could potentially also handle whitelisting certain requests that don't need authentication? On the other hand if you have a mixture of authentication requirements for one service maybe it's safer to have the rules clearly associated with the request handlers so the rules can't easily get out of sync.

One other thing I found a bit awkward with Tonic interceptors was that (and maybe this has changed in newer releases) there wasn't a public request extensions API and so there wasn't a very clean way of passing extra meta data from the interceptor to the request handlers apart from simply adding custom http headers (which you then needed to be extra careful to check aren't present in the original request) - hopefully the internal extensions API is public now. I wanted this so I could pass the username from the JWT claims on to the request handler, without needing to parse the JWT tokens more than once.

Btw, I also found that the maintainer of Tonic was super responsive to questions and feedback on Discord/Github incase there's anything about Tonic that could be changed to help for your use case.

**Comment by robertohuertasm** [comment]
Hi @rib, it seems that Cognito still doesn't have key rotation so your solution may work while they don't decide to change this behavior.

Regarding the `request extensions` I couldn't find a way to use them either. I've just asked in Discord to see if they have another strategy for these use cases. On my first attempt with interceptors I was using the `metadata` map for these purposes, the same as you proposed.

My current approach is having a function on each endpoint that needs authentication that validates the token and extracts the username for further validations. But then, you're tied to have this on each endpoint and be vigilant not to miss one of your protected endpoints. That's the trade-off. It works for my case, as I have a mixture of protected and unprotected endpoints but I totally understand that in a fully protected API, this is not the perfect solution in that case.

**Pull request merged**
